# backend/agents/shared/models.py
"""
Shared data models used for communication between agents, and for shaping
the legacy-compatible API response.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass
class OperationalDecision:
    """
    Structured output produced by the Ops Agent.

    Attributes:
        sku: Name/identifier of the SKU analyzed.
        action: "REORDER" or "MONITOR".
        needs_reorder: Whether the item requires reordering.
        inventory_gap: forecast_demand - available_stock.
        recommended_qty: Units to reorder, rounded up per business rules.
        safety_stock: Deterministically estimated safety stock buffer.
        reorder_point: Stock level at which reordering should trigger
            (forecast during lead time + safety_stock).
        inventory_status: One of NORMAL/LOW/CRITICAL/OUT_OF_STOCK.
        assignee: Role responsible for acting on this recommendation.
        recommendation_details: Human-readable recommendation text.
        reasoning: Human-readable explanation of the operational decision.
    """

    sku: str
    action: str
    needs_reorder: bool
    inventory_gap: int
    recommended_qty: int
    assignee: str
    recommendation_details: str
    reasoning: str
    safety_stock: int = 0
    reorder_point: int = 0
    inventory_status: str = "NORMAL"


@dataclass
class RiskAssessment:
    """
    Structured output produced by the Risk Agent.

    Attributes:
        sku: Name/identifier of the SKU assessed.
        risk_score: Deterministic risk score (0-100), computed in Python.
        risk_level: "LOW" / "MEDIUM" / "HIGH" / "CRITICAL".
        shortage_risk: Whether shortage contributes to this item's risk.
        expiry_risk: Whether expiry contributes to this item's risk.
        criticality: "CRITICAL" / "STANDARD".
        alert_level: Mirrors risk_level (kept for backward compatibility
            with callers that read alert_level).
        confidence_width: confidence_high - confidence_low, when provided.
        human_review_recommended: True if risk_score meets or exceeds
            HUMAN_REVIEW_RISK_THRESHOLD, meaning autonomous execution
            should be downgraded to manual review.
        reasoning: Human-readable explanation of the risk assessment.
    """

    sku: str
    risk_score: int
    risk_level: str
    shortage_risk: bool
    expiry_risk: bool
    criticality: str
    alert_level: str
    reasoning: str
    confidence_width: Optional[float] = None
    human_review_recommended: bool = False


@dataclass
class AuditRuleResult:
    """
    Outcome of a single deterministic Auditor rule check.

    Attributes:
        rule_name: Identifier of the rule (e.g. "NEGATIVE_STOCK").
        severity: One of WARNING / ERROR / BLOCKER.
        message: Human-readable (but LLM-independent) description of the
            failure, used as raw input for the LLM's summary — not
            generated by the LLM itself.
    """

    rule_name: str
    severity: str
    message: str


@dataclass
class AuditResult:
    """
    Structured output produced by the Auditor Agent.

    Attributes:
        approved: Whether the workflow is allowed to proceed.
        audit_status: "APPROVED" / "APPROVED_WITH_WARNINGS" / "REJECTED".
        failed_rules: Names of every rule that did not pass (flattened,
            kept for backward compatibility with existing consumers).
        warning_count: Number of WARNING-severity rule failures.
        blocking_errors: Number of BLOCKER-severity rule failures.
        error_count: Number of ERROR-severity rule failures.
        rule_results: Full detail (name, severity, message) for every
            failed rule.
        reasoning: Human-readable explanation of the approval/rejection.
    """

    approved: bool
    audit_status: str
    failed_rules: list = field(default_factory=list)
    warning_count: int = 0
    blocking_errors: int = 0
    error_count: int = 0
    rule_results: List[AuditRuleResult] = field(default_factory=list)
    reasoning: str = ""


@dataclass
class FinalDecision:
    """
    Structured output produced by the Report Agent.

    Attributes:
        sku: Name/identifier of the SKU.
        execution_allowed: Mirrors AuditResult.approved exactly.
        final_status: "EXECUTED" / "EXECUTED_WITH_WARNINGS" / "BLOCKED".
        recommended_action: The operational action being reported on.
        executive_summary: High-level LLM-generated summary.
        reasoning: LLM-generated explanation of the final status.
        generated_at: Timestamp of when this report was produced.
        report_sections: Structured executive report broken into named
            sections (inventory_summary, operational_decision,
            risk_assessment, audit_findings, final_recommendation,
            next_actions). Additive field — existing consumers that only
            read executive_summary/reasoning are unaffected.
    """

    sku: str
    execution_allowed: bool
    final_status: str
    recommended_action: str
    executive_summary: str
    reasoning: str
    generated_at: datetime
    report_sections: dict = field(default_factory=dict)


@dataclass
class LegacyDecisionResponse:
    """
    Typed representation of the API's legacy-compatible response shape.
    """

    status: Optional[str] = None
    message: Optional[str] = None
    details: Optional[str] = None
    sku_name: Optional[str] = None
    action: Optional[str] = None
    recommended_qty: Optional[int] = None
    assignee: Optional[str] = None
    reasoning: Optional[str] = None
    recommendation: Optional[str] = None
    risk_level: Optional[str] = None
    audit_status: Optional[str] = None
    failed_rules: Optional[List[str]] = None

    def to_dict(self) -> dict:
        return {
            key: value
            for key, value in self.__dict__.items()
            if value is not None
        }